'''
tweet_nouns.py: list of nouns used to build tweet
11 September 2020
Vicki Langer (@vicki_langer)
'''

# TODO: add more nouns

nouns = [
    # animals
    'mousey 🐭',
    'bunny rabbit 🐰',
    'bear 🐻',
    'panda 🐼',
    'koala 🐨',
    'monkey 🐒',
    'fox 🦊',
    'raccoon 🦝',
    'zebra 🦓',
    'giraffe 🦒',
    'kangaroo 🦘',
    'camel 🐪',
    'flamingo 🦩',
    'kitteh 🐱',
    'doggo 🐶',
    'elephant 🐘',
    'emu',
    'hamster 🐹',
    'bat 🦇',
    'sloth 🦥',
    'danger noodle 🐍',
    'snek 🐍',
    'spider',
    'lemur',
    'kitteh',
    'betta fish',
    'antelope',
    'salamander',
    'dolphin 🐬',
    'mole',
    'octopus 🐙',
    'pangolin',
    'narwhal 🦄',
    'axolotl',
    'aardvark',
    'platypus',
    'California condor',
    'lynx',
    'otter 🦦',

    # clothing items
    'flannel shirt',
    'bandana',
    'kippah',
    'boots 🥾',
    'wallet',
    'earmuffs',
    'hijab',
    'headphones 🎧',
    'handbag 👛',
    'head scarf',
    'haltertop',
    'house shoes',
    'caftan',
    'ascot',
    'crop top',
    'beret',
    'party hat',
    'turtle neck',
    'windbreaker',
    'kimono',
    'helmet',

    # foods
    'pizza',
    'chicken noodle soup',
    'protien shake',
    'tuna',
    'cheeseburger 🍔',
    'french fries 🍟',
    'mashed potatoes',
    'lasagna',
    'fried chicken 🍗',
    'peanut butter',
    'chili con carne',
    'fortune cookie 🥠',
    'arroz con pollo',
    'quesadilla',
    'pierogies',
    'bagel 🥯',
    'chicken tikka masala',
    'chicken and dumplings',
    'ratatouille',
    'ramen',
    '@tacobell grilled cheese burrito 🌯',
    'poutine',
    'meatloaf',
    'casserole',
    'moussaka',
    'gyros',
    'matzah ball',
    'stroganoff',
    'mango',
    'macaroni and cheese',

    # computer things
    'laptop',
    'keyboard',
    'dual-monitor desk setup',
    'laptop stand',
    'charging cables',
    'wireless mouse',
    'wireless touchpad',
    'printer',

    # old tech
    'iMac G3',
    'typewriter',
    'fax machine',
    'CRT computer monitor',
    'answering machine',
    'wired landlines',
    'pagers/beeper',
    'rotary telephone',
    'flip phones',
    'MP3 player',
    'PDA',
    'floppy disc',
    'phonebook',
    'portatable DVD player',
    'dial-up modem',
    'walkman',
    'betamax',
    'dot-matrix printer',

    # video game consoles
    'Atari',
    'Sega',
    'Intellivision',
    'Commodore 64',
    'SNES',
    'PlayStation',
    'N64',
    'Dreamcast',
    'GameCube',
    'Xbox',
    'Wii',
    'Switch',
    'GameBoy',
    'Atari Lynx',
    'Sega Game Gear',
    'Nintendo DS',
    'PSP',
    'PS Vita',
]
