'''
tweet_nouns.py: list of nouns used to build tweet
11 September 2020
Vicki Langer (@vicki_langer)
'''

# TODO: add more nouns

nouns = [
    # animals
    'mousey 🐭',
    'bunny rabbit 🐰',
    'bear 🐻',
    'panda 🐼',
    'koala 🐨',
    'monkey 🐒',
    'fox 🦊',
    'raccoon 🦝',
    'zebra 🦓',
    'giraffe 🦒',
    'kangaroo 🦘',
    'camel 🐪',
    'flamingo 🦩',
    'kitteh 🐱',
    'doggo 🐶',
    'elephant 🐘',
    'emu',
    'hamster 🐹',
    'bat 🦇',
    'sloth 🦥',
    'danger noodle 🐍',
    'snek 🐍',
    'spider',
    'lemur',
    'kitteh',
    'betta fish',
    'antelope',
    'salamander',
    'dolphin 🐬',
    'mole',
    'octopus 🐙',
    'pangolin',
    'narwhal 🦄',
    'axolotl',
    'aardvark',
    'platypus',
    'California condor',
    'lynx',
    'otter 🦦',

    # clothing items
    'flannel shirt',
    'bandana',
    'kippah',
    'boots',
    'wallet',
    'earmuffs',
    'hijab',
    'headphones',
    'handbag',
    'head scarf',
    'haltertop',
    'house shoes',
    'caftan',
    'ascot',
    'crop top',
    'beret',
    'party hat',
    'turtle neck',
    'windbreaker',
    'kimono',
    'helmet',

    # foods
    'pizza',
    'chicken noodle soup',
    'protien shake',
    'tuna',
    'cheeseburger',
    'french fries',
    'mashed potatoes',
    'lasagna',
    'fried chicken',
    'peanut butter',
    'chili con carne',
    'arroz con pollo',
    'quesadilla',
    'pierogies',
    'chicken tikka masala',
    'chicken and dumplings',
    'ratatouille',
    'ramen',
    'poutine',
    'meatloaf',
    'casserole',
    'moussaka',
    'gyros',
    'matzah ball',
    'stroganoff',
    'mango',
    'macaroni and cheese',
]
