'''
tweet_nouns.py: list of nouns used to build tweet.py
11 September 2020
Vicki Langer (@vicki_langer)
'''

# TODO: add more nouns, in alphabetical order
# NOTE: nouns should be singular (e.g. 'boot' not 'boots')
# NOTE: must make sense in "{adjective} {label} {noun}" (example: tiny queer [something])
# NOTE: must fit in a tweet, so not longer than this line -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|

nouns = [
    # animals
    'aardvark',
    'antelope',
    'axolotl',
    'bat 🦇',
    'Bat 🦇',
    'bear 🐻',
    'betta fish',
    'Bird',
    'buffalo 🐃',
    'bunny rabbit 🐰',
    'California condor',
    'camel 🐪',
    'capybara',
    'cat 🐈',
    'cat',
    'cow 🐄',
    'Cow',
    'danger noodle 🐍',
    'Dog 🐶',
    'doggo 🐶',
    'dolphin 🐬',
    'duck 🦆',
    'elephant 🐘',
    'elephant',
    'emu',
    'flamingo 🦩',
    'fox 🦊',
    'frog 🐸',
    'giraffe 🦒',
    'Giraffe 🦒',
    'hamster 🐹',
    'hedgehog 🦔',
    'horse 🐎',
    'hyacinth macaw',
    'kangaroo 🦘',
    'kitteh 🐱',
    'kitten',
    'koala 🐨',
    'kookaburra',
    'lemur',
    'lion 🦁',
    'lynx',
    'mole',
    'monkey 🐒',
    'mousey 🐭',
    'narwhal 🦄',
    'octopus 🐙',
    'otter 🦦',
    'otter',
    'owl 🦉',
    'panda 🐼',
    'pangolin',
    'parrot 🦜',
    'penguin 🐧',
    'platypus',
    'Polar Bear',
    'puffin 🐧',
    'quokka',
    'raccoon 🦝',
    'rhino 🦏',
    'salamander',
    'seal',
    'shark 🦈',
    'sheep 🐑',
    'sloth 🦥',
    'snake 🐍',
    'spider',
    'swan 🦢',
    'trilobite',
    'velociraptor',
    'wolf',
    'zebra 🦓',

    # clothing items
    'ascot',
    'ball gown',
    'bandana',
    'bell-bottoms',
    'belt',
    'beret',
    'bikini 👙',
    'blazer',
    'bloomer',
    'blue jeans 👖',
    'boot 🥾',
    'caftan',
    'cravat',
    'crop top',
    'dungaree',
    'dynamo',
    'earmuff',
    'feather boa',
    'flannel shirt',
    'frock',
    'glove',
    'gown',
    'haltertop',
    'handbag 👛',
    'head scarf',
    'headphone 🎧',
    'helmet',
    'hijab',
    'hoodie',
    'house shoe',
    'jacket',
    'jumper',
    'kimono 👘',
    'kippah',
    'murse',
    'neon fanny pack',
    'party hat',
    'romper',
    'sari 🥻',
    'skinny jeans',
    'slipper',
    'sneaker',
    'sock 🧦',
    'sunglasses 🕶️',
    't-shirt 👕',
    'top hat 🎩',
    'turtle neck',
    'vest',
    'wallet',
    'windbreaker',


    # foods
    'almond',
    'ambrosia salad',
    'apple pie 🥧',
    'arroz con pollo',
    'bagel 🥯',
    'banana split',
    'banana',
    'bavarian beer 🍺',
    'biryani',
    'bread🍞',
    'brownie',
    'butter chicken',
    'cadbury🍫',
    'carrot',
    'casserole',
    'challah bread',
    'cheeseburger 🍔',
    'chicken and dumpling',
    'chicken dinner',
    'chicken noodle soup',
    'chicken tikka masala',
    'chili baby corn',
    'chili con carne',
    'chole bhature',
    'chowmin',
    'chutney',
    'coffee',
    'congee',
    'cranberry',
    'croissant 🥐',
    'cucumber',
    'currywurst',
    'dahi',
    'dosa',
    'doughnut 🍩',
    'eggplant',
    'fish and chips',
    'fortune cookie 🥠',
    'french fry 🍟',
    'fried chicken 🍗',
    'fried plantain',
    'gefilte fish',
    'guacamole 🥑',
    'gulab jamun',
    'gyro',
    'ham sandwich',
    'halwa',
    'ice-cream',
    'idli sambhar',
    'jalebi',
    'kachori',
    'kheer',
    'Khia sangia',
    'khichdi',
    'kofta',
    'lasagna',
    'lassi',
    'lechon',
    'lemonade',
    'maal-pua',
    'macaroni and cheese',
    'mango',
    'mashed potatoes',
    'matzah ball',
    'meatloaf',
    'moussaka',
    'mousse',
    'naan',
    'noodle',
    'omlette',
    'onion soup',
    'oxtail',
    'pancake'
    'pav bhaji',
    'peanut butter',
    'peanut',
    'pho',
    'pierogi',
    'pizza 🍕',
    'pomegranate',
    'popcorn 🍿',
    'poutine',
    'pretzel 🥨',
    'protein shake',
    'pulao',
    'quesadilla',
    'rainbow cake',
    'ramen',
    'ratatouille',
    'roti',
    'salmon',
    'samosa',
    'samosa',
    'spam',
    'stroganoff',
    'sushi 🍣',
    'taco 🌮',
    'tacobell grilled cheese burrito 🌯',
    'tandoori chicken',
    'tea☕',
    'tiramisu',
    'tomato soup',
    'trifle',
    'tuna',
    'vada pav',
    'waffle',
    'watermelon',
    'yoghurt',

    # computer things
    'adapter',
    'antivirus software',
    'audio jack',
    'carrying bag',
    'charging cable',
    'CPU',
    'desktop',
    'dual-monitor desk setup',
    'ethernet cable',
    'external hard disk',
    'graphics card'
    'hard disk',
    'joystick',
    'kernel'
    'keyboard',
    'laptop stand',
    'laptop',
    'laptop table',
    'memory card',
    'microphone',
    'motherboard',
    'mouse pad',
    'pen drive',
    'port',
    'printer',
    'quad-core processor',
    'scanner',
    'socket',
    'software',
    'speaker',
    'SSD',
    'stylus pen',
    'trackpad',
    'usb hub',
    'virus',
    'webcam',
    'wireless mouse',
    'wireless touchpad',

    # old tech
    'answering machine',
    'betamax',
    'cassette player',
    'clicky mechanical keyboard',
    'CRT computer monitor',
    'dial-up modem',
    'dot-matrix printer',
    'fax machine 📠',
    'flip phone',
    'floppy disc',
    'gramophone',
    'iMac G3',
    'landline ☎️',
    'MP3 player',
    'pagers/beeper 📟',
    'PDA',
    'phonebook',
    'portatable DVD player',
    'radio'
    'rotary telephone',
    'steno machine',
    'telegraph'
    'typewriter',
    'VCR',
    'VHS',
    'walkman',

    # video game consoles
    'Adventure Vision',
    'Atari',
    'Commodore 64',
    'Dreamcast',
    'GameBoy',
    'GameCube',
    'Intellivision',
    'N64',
    'Nintendo DS',
    'Nintendo Switch',
    'PlayStation',
    'PS Vita',
    'PS5',
    'PSP',
    'Sega Game Gear',
    'Sega',
    'SNES',
    'Virtual Boy',
    'Wii',
    'Xbox X',
    'Xbox',

    # nature
    'archipelago',
    'aurora',
    'beach 🏖',
    'body of water',
    'bolt of lightening ⚡',
    'breeze',
    'campfire 🔥',
    'cave',
    'cliff',
    'cloud over the sun ⛅',
    'cloud',
    'coast',
    'desert',
    'Earth 🌎',
    'flower 🌹',
    'hill',
    'island 🏝️',
    'meadow',
    'moon 🌑',
    'moonlit sky'
    'mountain ⛰️',
    'oak tree',
    'petrichor',
    'rain',
    'rainbow 🌈',
    'rainforest',
    'rock',
    'sand',
    'sea'
    'seashell',
    'sleet',
    'snow',
    'snowflake ❄',
    'some moss',
    'star',
    'stone',
    'sunflower 🌻',
    'swamp',
    'the swamp creature',
    'trail in the woods',
    'volcano',
    'wind',

    # classroom objects
    'back pack',
    'bench',
    'binder clip',
    'board',
    'book',
    'box',
    'calculator',
    'chalk',
    'compass',
    'duster',
    'eraser',
    'geometry box',
    'highlighter',
    'liquid paper',
    'marker'
    'marker',
    'notebook',
    'paint',
    'pen',
    'pencil case',
    'pencil sharpener',
    'pencil',
    'protractor',
    'ruler',
    'scissor',
    'stapler',
    'stencil',
    'water bottle',

    # rpg classes\skins
    'archer',
    'bard',
    'berserker',
    'cleric',
    'dragoon',
    'fae',
    'fighter',
    'ghost',
    'ghoul',
    'mage',
    'mortal',
    'necromancer',
    'queen',
    'rogue',
    'shadowknight',
    'sorcerer',
    'summoner',
    'vampire',
    'vigilante',
    'warlock',
    'werewolf',
    'witch',
    'wizard',

    # goofy things
    # NOTE: must make sense after "{adjective} {label}" (example: tiny queer [something])
    '3 day old opened can of tuna',
    'app that has stories but really shouldn\'t have them',
    'automatic kitty litter box',
    'barely-functioning homemade water bottle bong',
    'blurry photo of feet from an @OnlyFans subscription',
    'cake that perfectly resembles an intricate knitted blanket',
    'castle',
    'child asking "why" for the fiftieth time',
    'color',
    'graphic novel memoir',
    'hand drawn picture of a stick family hanging in The Louvre',
    'horribly biased machine learning code out to screw over the most vulnerable',
    'indie song about friendship',
    'ladle',
    'lighthouse in the darkness',
    'mitten still on the ground from last winter',
    'mom in sweatpants',
    'mostly slept through @Netflix series',
    'mysterious burrito with no owner',
    'mysterious piñata hanging in a hallway',
    'null bus',
    'null haus',
    'old folk-tale that kept you up at night',
    'outdoor @OnePeloton',
    'partially eaten chicken salad sandwich',
    'pink bra strap',
    'pipe made out of an apple',
    'ray of light in the distance',
    'scream into the void',
    'stack of half-finished side projects',
    'subscription box of cat toys',
    'surprise casserole',
    'treadmill, but only for using outside',
    'treekisser',
    'twitter meme trend',
    'unintended consequence of a homogenous software engineering team',
    'wheelchair-bomb',
    'wrongness parfait',

    # types of movies
    'action movie',
    'adventure movie',
    'animation movie',
    'comedy movie',
    'dramatic movie',
    'family movie'
    'historical movie',
    'horror movie',
    'mystery movie',
    'romance movie',
    'romantic movie',
    'romcom movie',
    'sci-fi movie',
    'thriller movie',

    # grooming items
    'bodywash',
    'cleanser',
    'comb',
    'curling-iron',
    'epilator',
    'face scrub',
    'face wash',
    'foot massager',
    'hair crimper',
    'hair dryer',
    'lip gloss',
    'mirror',
    'mouthwash',
    'razor',
    'red lipstick',
    'sanitary napkin',
    'sanitizer',
    'serum',
    'soap',
    'tampon',
    'toothbrush',
    'toothpaste',
    'trimmer',
    'wax-strip',

    # sports things
    'archery target',
    'badminton net',
    'badminton racket',
    'baseball field',
    'basketball',
    'batting glove',
    'billiards stick',
    'chess board',
    'cricket paddle',
    'cricket bat',
    'cricket ball',
    'dartboard',
    'dodgeball',
    'golf club',
    'handball',
    'hula hoop',
    'ice hockey rink',
    'karate dojo',
    'lacrosse stick',
    'polo team',
    'racquetball court',
    'rugby ball',
    'snorkel gear',
    'soccer goalie',
    'softball bat',
    'squash team',
    'table tennis paddle',
    'tennis court',
    'tug of war rope',
    'volley ball net',
    'water polo',

    # fashion trends
    'chelsea boot',
    'cuffed pants and sleeves',
    'tight-rolled pants',
    'asymmetrical undercut',
    'septum piercing',
    'rolled pant legs',
    'folded shirt sleeves',
    'cuffed jeans',

    # queer things
    '@autostraddle article',
    'chosen family',
    'drag king',
    'drag queen',
    'drag brunch',
    'french cuff',
    'gogo boy',
    'newest issue of @ftmmagazine',
    'newly released book chosen for the Stonewall Book Awards (@GLBTRT)',
    'old issue of @TheAdvocateMag',
    'Sunday brunch',
    'tight-rolled pant',
    'wall plastered with varying pride flags',
    '@autostraddle article',
]
