'''
tweet_nouns.py: list of nouns used to build tweet.py
11 September 2020
Vicki Langer (@vicki_langer)
'''

# TODO: add more nouns, in alphabetical order
# NOTE: nouns should be singular (e.g. 'boot' not 'boots')
# NOTE: must make sense in "{adjective} {label} {noun}" (example: tiny queer [something])
# NOTE: must fit in a tweet, so not longer than this line -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|

nouns = [
    # animals
    'aardvark',
    'alligator 🐊',
    'anteater',
    'antelope',
    'axolotl',
    'baboon',
    'badger',
    'bat 🦇',
    'Bat 🦇',
    'bear 🐻',
    'betta fish',
    'Bird',
    'boar 🐗',
    'buffalo 🐃',
    'bunny rabbit 🐰',
    'butterfly',
    'California condor',
    'camel 🐪',
    'capybara',
    'cat 🐈',
    'cat',
    'cheetah',
    'chicken 🐔',
    'cobra',
    'cow 🐄',
    'crab 🦀',
    'crocodile 🐊',
    'danger noodle 🐍',
    'deer 🦌',
    'dinosaur',
    'dodo',
    'Dog 🐶',
    'Doggie 🐶',
    'doggo 🐶',
    'dolphin 🐬',
    'donkey',
    'dove 🕊️',
    'duck 🦆',
    'eagle 🦅',
    'elephant 🐘',
    'elephant',
    'emu',
    'flamingo 🦩',
    'fox 🦊',
    'frog 🐸',
    'giraffe 🦒',
    'goose',
    'goat 🐐',
    'hamster 🐹',
    'hawk',
    'hedgehog 🦔',
    'hippo',
    'honeybee 🐝',
    'horse 🐎',
    'hyacinth macaw',
    'hyena',
    'iguana',
    'jackal',
    'kangaroo 🦘',
    'kitteh 🐱',
    'kitten',
    'koala 🐨',
    'kookaburra',
    'lemur',
    'leopard',
    'lion 🦁',
    'lizard 🦎',
    'lobster 🦞',
    'lynx',
    'meerkat',
    'mockingbird',
    'mole',
    'monkey 🐒',
    'mouse 🐭',
    'narwhal 🦄',
    'octopus 🐙',
    'opossum',
    'orangutan 🦧',
    'otter 🦦',
    'owl 🦉',
    'oyster 🦪',
    'panda 🐼',
    'pangolin',
    'panther',
    'parrot 🦜',
    'peacock 🦚',
    'penguin 🐧',
    'pigeon',
    'platypus',
    'pig 🐖',
    'Polar Bear',
    'Pony',
    'puffin 🐧',
    'quokka',
    'raccoon 🦝',
    'rat 🐀',
    'rhino 🦏',
    'rooster 🐓',
    'salamander',
    'scorpion 🦂',
    'seal',
    'shark 🦈',
    'shrimp 🦐',
    'sheep 🐑',
    'skunk 🦨',
    'sloth 🦥',
    'snake 🐍',
    'spider',
    'squid 🦑',
    'swan 🦢',
    'tern',
    'tiger 🐅',
    'tortoise',
    'toucan',
    'trilobite',
    'turkey 🦃',
    'turtle 🐢',
    'velociraptor',
    'viper🐍',
    'vulture',
    'warthog',
    'whale 🐋',
    'wolf',
    'wolverine',
    'zebra 🦓',
    
    #body organs
    'arm',
    'eye',
    'finger',
    'foot',
    'hair',
    'hand',
    'head',
    'knee',
    'leg',
    'nail',
    'neck',
    'nose',
    'toe',
    'tooth',

    #insect 
    'ant 🐜',
    'caterpillar 🐛',
    'cockroach',
    'cricket 🦗',
    'honeybee 🐝',
    'ladybug 🐞',
    'mosquito 🦟',
    'spider 🕷',
    
    # clothing items
    'ascot',
    'ball gown',
    'bandana',
    'beanie',
    'bell-bottoms',
    'belt',
    'beret',
    'bikini 👙',
    'bennie',
    'blazer',
    'bloomer',
    'blue jeans 👖',
    'boot 🥾',
    'caftan',
    'cap 🧢',
    'cravat',
    'crop top',
    'corset',
    'diving mask 🤿',
    'dungaree',
    'dynamo',
    'earmuff',
    'feather boa',
    'flannel shirt',
    'flip flops',
    'frock',
    'glove',
    'goggles 🥽',
    'gown',
    'haltertop',
    'handbag 👛',
    'hat',
    'head scarf',
    'headphone 🎧',
    'helmet',
    'hijab',
    'hoodie',
    'house shoe',
    'jacket',
    'joggers',
    'jumper',
    'jumpsuit',
    'kimono 👘',
    'kippah',
    'murse',
    'neon fanny pack',
    'party hat',
    'romper',
    'sari 🥻',
    'scarf',
    'skinny jeans',
    'skirt',
    'slipper',
    'sneaker',
    'sock 🧦',
    'sunglasses 🕶️',
    't-shirt 👕',
    'top hat 🎩',
    'toque',
    'turtle neck',
    'vest',
    'wallet',
    'windbreaker',
    'yeezy',


    # foods
    'almond',
    'ambrosia salad',
    'apple',
    'apple pie 🥧',
    'applesauce',
    'apricot',
    'arroz con pollo',
    'bacon 🥓',
    'bagel 🥯',
    'baguette 🥖',
    'bologna',
    'banana split',
    'banana 🍌',
    'bavarian beer 🍺',
    'biryani',
    'bread🍞',
    'brownie',
    'burrito 🌯',
    'butter chicken',
    'cadbury🍫',
    'cake',
    'carrot',
    'candy 🍬',
    'casserole',
    'cereal',
    'challah bread',
    'chard',
    'cheese',
    'cheeseburger 🍔',
    'cherries',
    'chicken and dumpling',
    'chicken dinner',
    'chicken noodle soup',
    'chicken tikka masala',
    'chili baby corn',
    'chili con carne',
    'chocolate bar 🍫',
    'chole bhature',
    'chowmin',
    'chutney',
    'coconut 🥥',
    'cookie',
    'coffee',
    'congee',
    'corn',
    'cranberry',
    'crepe',
    'croissant 🥐',
    'cucumber',
    'cupcake',
    'currywurst',
    'Custard 🍮',
    'dahi',
    'dosa',
    'doughnut 🍩',
    'dumpling 🥟',
    'egg',
    'eggplant',
    'egg roll',
    'fish and chips',
    'fortune cookie 🥠',
    'french fry 🍟',
    'fried chicken 🍗',
    'fried plantain',
    'fried rice',
    'garlic bread',
    'gefilte fish',
    'grapes 🍇',
    'green apple 🍏',
    'guacamole 🥑',
    'gulab jamun',
    'gyro',
    'ham',
    'ham sandwich',
    'halwa',
    'hashbrown',
    'hotdog 🌭',
    'hummus',
    'ice-cream',
    'idli sambhar',
    'jackfruit',
    'jalebi',
    'kachori',
    'kefir',
    'kheer',
    'Khia sangia',
    'khichdi',
    'kimchi',
    'kiwi',
    'kofta',
    'lasagna',
    'lassi',
    'lechon',
    'lemonade',
    'lentils',
    'maal-pua',
    'macaroni and cheese',
    'mango',
    'martini 🍸',
    'mashed potatoes',
    'matzah ball',
    'meatball',
    'meatloaf',
    'melon 🍈',
    'mojito',
    'moussaka',
    'mousse',
    'mushroom',
    'muffin',
    'naan',
    'noodle',
    'omlette',
    'onion soup',
    'oxtail',
    'pancake',
    'paneer',
    'paratha',
    'pasta',
    'pav bhaji',
    'peach 🍑',
    'peanut butter',
    'peanut',
    'pear',
    'pho',
    'pie',
    'pierogi',
    'pizza 🍕',
    'pomegranate',
    'poki bowl',
    'popcorn 🍿',
    'poutine',
    'potato',
    'potluck',
    'pretzel 🥨',
    'protein shake',
    'pulao',
    'pumpkin',
    'quesadilla',
    'quinoa',
    'rainbow cake',
    'ramen',
    'rasogulla',
    'ratatouille',
    'rice',
    'rice Ball 🍙',
    'roti',
    'salad',
    'salmon',
    'salsa',
    'samosa',
    'sandwich',
    'sausage',
    'spaghetti 🍝',
    'spam',
    'stroganoff',
    'sushi 🍣',
    'Szechuan',
    'taco 🌮',
    'tacobell grilled cheese burrito 🌯',
    'tandoori chicken',
    'tea☕',
    'tiramisu',
    'tofu',
    'tomato soup',
    'trifle',
    'tuna',
    'vada pav',
    'waffle 🧇',
    'watermelon 🍉',
    'yoghurt',


     #insect 
    'ant',
    'bee',
    'buttrefly',
    'caterpillar',
    'cockroach',
    'ladybug',

    
    # computer things
    'adapter',
    'antivirus software',
    'audio jack',
    'bandwidth',
    'bluetooth',
    'carrying bag',
    'charging cable',
    'CPU',
    'desktop',
    'dual-monitor desk setup',
    'ethernet cable',
    'external hard disk',
    'firewall',
    'graphics card',
    'hard disk',
    'HDMI',
    'heat sink',
    'joystick',
    'kernel',
    'keyboard',
    'laptop stand',
    'laptop',
    'laptop table',
    'memory card',
    'microphone',
    'monitor',
    'motherboard',
    'mouse pad',
    'pen drive',
    'port',
    'printer',
    'quad-core processor',
    'RAM',
    'ROM',
    'scanner',
    'socket',
    'software',
    'speaker',
    'SSD',
    'stylus pen',
    'thumb drive',
    'trackpad',
    'usb hub',
    'virus',
    'webcam',
    'wireless mouse',
    'wireless touchpad',

    # old tech
    'answering machine',
    'betamax',
    'cassette player',
    'clicky mechanical keyboard',
    'CRT computer monitor',
    'dial-up modem',
    'dot-matrix printer',
    'fax machine 📠',
    'flip phone',
    'floppy disc',
    'gramophone',
    'iMac G3',
    'landline ☎️',
    'MP3 player',
    'pagers/beeper 📟',
    'PDA',
    'phonebook',
    'portable DVD player',
    'radio',
    'rotary telephone',
    'steno machine',
    'telegraph',
    'typewriter',
    'VCR',
    'VHS',
    'walkman',
    'floppy disk',

    # video game consoles
    'Adventure Vision',
    'Atari',
    'Commodore 64',
    'Dreamcast',
    'GameBoy',
    'GameCube',
    'Intellivision',
    'N64',
    'Nintendo DS',
    'Nintendo Switch',
    'Ouya',
    'PlayStation',
    'PS Vita',
    'PS1',
    'PS2',
    'PS3',
    'PS4',
    'PS5',
    'PSP',
    'Sega',
    'Sega Game Gear',
    'Sega Saturn',
    'SNES',
    'Virtual Boy',
    'Wii',
    'Wii U',
    'Xbox',
    'Xbox 360',
    'Xbox 1',
    'Xbox X',

    # nature
    'archipelago',
    'aurora',
    'beach 🏖',
    'body of water',
    'bolt of lightning ⚡',
    'breeze',
    'campfire 🔥',
    'cave',
    'cliff',
    'cloud over the sun ⛅',
    'cloud',
    'coast',
    'desert',
    'Earth 🌎',
    'drizzle',
    'flower 🌹',
    'forest',
    'hill',
    'island 🏝️',
    'lake',
    'logs',
    'meadow',
    'moon 🌑',
    'moonlit sky',
    'mountain ⛰️',
    'oak tree',
    'ocean',
    'pebble',
    'petrichor',
    'pond',
    'rain',
    'rainbow 🌈',
    'rainforest',
    'river',
    'rock',
    'sand',
    'sea',
    'seashell',
    'sky',
    'sleet',
    'snow',
    'snowflake ❄',
    'some moss',
    'star',
    'stone',
    'storm',
    'sunflower 🌻',
    'sunset',
    'swamp',
    'spring',
    'the swamp creature',
    'thunder',
    'trail in the woods',
    'volcano',
    'wasteland',
    'wind',

    # classroom objects
    'back pack',
    'bench',
    'binder clip',
    'board',
    'book',
    'box',
    'calculator',
    'chalk',
    'compass',
    'duster',
    'eraser',
    'geometry box',
    'highlighter',
    'liquid paper',
    'lunch box',
    'marker',
    'notebook',
    'paint',
    'pen',
    'pencil case',
    'pencil sharpener',
    'pencil',
    'protractor',
    'ruler',
    'scissor',
    'stapler',
    'stencil',
    'water bottle',
    'whiteboard',

    # rpg classes\skins
    'assassin',
    'archer',
    'bard',
    'berserker',
    'boss',
    'cleric',
    'dragon 🐲',
    'fae',
    'fighter',
    'ghost',
    'ghoul',
    'immortal',
    'king',
    'knight',
    'mage',
    'mortal',
    'necromancer',
    'prince',
    'princess',
    'queen',
    'rogue',
    'shadowknight',
    'sorcerer',
    'summoner',
    'vampire',
    'vigilante',
    'warlock',
    'werewolf',
    'witch',
    'witcher',
    'wizard',
    

    # goofy things
    # NOTE: must make sense after "{adjective} {label}" (example: tiny queer [something])
    '3 day old opened can of tuna',
    'app that has stories but really shouldn\'t have them',
    'automatic kitty litter box',
    'barely-functioning homemade water bottle bong',
    'blurry photo of feet from an @OnlyFans subscription',
    'cake that perfectly resembles an intricate knitted blanket',
    'castle',
    'child asking "why" for the fiftieth time',
    'color',
    'graphic novel memoir',
    'hand drawn picture of a stick family hanging in The Louvre',
    'horribly biased machine learning code out to screw over the most vulnerable',
    'indie song about friendship',
    'ladle',
    'lighthouse in the darkness',
    'mitten still on the ground from last winter',
    'mom in sweatpants',
    'mostly slept through @Netflix series',
    'mysterious burrito with no owner',
    'mysterious piñata hanging in a hallway',
    'null bus',
    'null haus',
    'old folk-tale that kept you up at night',
    'outdoor @OnePeloton',
    'partially eaten chicken salad sandwich',
    'pink bra strap',
    'pipe made out of an apple',
    'ray of light in the distance',
    'scream into the void',
    'stack of half-finished side projects',
    'subscription box of cat toys',
    'surprise casserole',
    'treadmill, but only for using outside',
    'treekisser',
    'twitter meme trend',
    'unintended consequence of a homogenous software engineering team',
    'wheelchair-bomb',
    'wrongness parfait',

    # types of movies
    'action movie',
    'anime movie',
    'adventure movie',
    'animation movie',
    'comedy movie',
    'cartoon movie',
    'dramatic movie',
    'family movie',
    'fiction movie',
    'historical movie',
    'horror movie',
    'mystery movie',
    'non-fiction movie',
    'romance movie',
    'romantic movie',
    'romcom movie',
    'suspense movie',
    'sci-fi movie',
    'thriller movie',

    # grooming items
    'bodywash',
    'cleanser',
    'comb',
    'curling-iron',
    'epilator',
    'face scrub',
    'face wash',
    'foot massager',
    'hair crimper',
    'hair dryer',
    'lip gloss',
    'mirror',
    'mouthwash',
    'razor',
    'red lipstick',
    'sanitary napkin',
    'sanitizer',
    'serum',
    'soap',
    'tampon',
    'toothbrush',
    'toothpaste',
    'trimmer',
    'wax-strip',

    # sports things
    'archery target',
    'badminton net',
    'badminton racket',
    'baseball field',
    'basketball',
    'batting glove',
    'billiards stick',
    'carom',
    'chess board',
    'cricket paddle',
    'cricket bat',
    'cricket ball',
    'dartboard',
    'discuss',
    'dodgeball',
    'frisbee',
    'goal post',
    'golf club',
    'handball',
    'hula hoop',
    'ice hockey rink',
    'karate dojo',
    'lacrosse stick',
    'polo team',
    'racquetball court',
    'rugby ball',
    'shotput',
    'snorkel gear',
    'soccer goalie',
    'softball bat',
    'spikes',
    'squash team',
    'table tennis paddle',
    'tennis court',
    'tug of war rope',
    'volley ball net',
    'water polo',
    'wicket',

    # fashion trends
    'chelsea boot',
    'cuffed pants and sleeves',
    'tight-rolled pants',
    'asymmetrical undercut',
    'septum piercing',
    'rolled pant legs',
    'folded shirt sleeves',
    'cuffed jeans',
    'oversized jeans',
    'Oversized Victorian Sleeves',
    'Maxi Faux Leather Coats',
    'Ripped Stockings',
    'Faux Fur Sandals',
    'Bucket Hats',
    'Shrunken Bags',
    'baggy trousers',
    'poofy shoulders',

    # queer things
    '@autostraddle article',
    'chosen family',
    'drag king',
    'drag queen',
    'drag brunch',
    'french cuff',
    'gogo boy',
    'newest issue of @ftmmagazine',
    'newly released book chosen for the Stonewall Book Awards (@GLBTRT)',
    'old issue of @TheAdvocateMag',
    'Sunday brunch',
    'tight-rolled pant',
    'wall plastered with varying pride flags',
    '@autostraddle article',
]
