'''
tweet_nouns.py: list of nouns used to build tweet.py
11 September 2020
Vicki Langer (@vicki_langer)
'''

# TODO: add more nouns, in alphabetical order
# NOTE: nouns should be singular (e.g. 'boot' not 'boots')
# NOTE: must make sense in "{adjective} {label} {noun}" (example: tiny queer [something])
# NOTE: must fit in a tweet, so not longer than this line -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|

nouns = [
    # animals
    'aardvark',
    'African wild dog',
    'agouti',
    'albatross',
    'alpaca 🦙',
    'alligator 🐊',
    'anteater',
    'antelope',
    'armadillo',
    'axolotl',
    'baboon',
    'badger',
    'bald eagle 🦅',
    'bandicoot',
    'bat 🦇',
    'bear 🐻',
    'betta fish',
    'bird',
    'bison',
    'boa constrictor',
    'boar 🐗',
    'bobcat',
    'buffalo 🐃',
    'bunny rabbit 🐰',
    'bushbaby'
    'butterfly',
    'caiman',
    'California condor',
    'Canada goose',
    'camel 🐪',
    'capybara',
    'cardinal',
    'caribou',
    'cat 🐈',
    'chameleon',
    'cheetah',
    'chickadee,'
    'chicken 🐔',
    'chimpanzee',
    'chinchilla',
    'chipmunk',
    'civet',
    'coatimundi',
    'cobra',
    'cockatoo',
    'colobus monkey',
    'cougar',
    'cow 🐄',
    'coyote',
    'crab 🦀',
    'crane',
    'crocodile 🐊',
    'danger noodle 🐍',
    'deer 🦌',
    'dingo',
    'dinosaur',
    'dodo',
    'Dog 🐶',
    'Doggie 🐶',
    'doggo 🐶',
    'dolphin 🐬',
    'donkey',
    'dove 🕊️',
    'downy woodpecker',
    'duck 🦆',
    'eagle 🦅',
    'echidna',
    'egret',
    'elephant 🐘',
    'elk',
    'emu',
    'falcon',
    'ferret',
    'finch',
    'flamingo 🦩',
    'flying fox',
    'fox 🦊',
    'frog 🐸',
    'gazelle',
    'gecko',
    'gerbil',
    'giant anteater',
    'gila monster',
    'giraffe 🦒',
    'goat 🐐',
    'golden eagle',
    'goose',
    'gorilla',
    'grizzly bear',
    'groundhog',
    'hamster 🐹',
    'harbor seal',
    'hare',
    'hawk',
    'hedgehog 🦔',
    'hen',
    'heron',
    'hippo',
    'honey badger',
    'honeybee 🐝',
    'horse 🐎',
    'hyacinth macaw',
    'hyena',
    'hyrax',
    'ibex',
    'ibis',
    'iguana',
    'impala',
    'jackal',
    'jackrabbit',
    'jaguar',
    'kangaroo 🦘',
    'killer whale',
    'kinkajou',
    'kitteh 🐱',
    'kitten',
    'koala 🐨',
    'komodo dragon',
    'kookaburra',
    'lemming',
    'lemur',
    'leopard',
    'lion 🦁',
    'lizard 🦎',
    'llama 🦙',
    'lobster 🦞',
    'loris',
    'lynx',
    'macaque',
    'macaw',
    'magpie',
    'mallard',
    'manatee',
    'marmot',
    'marten',
    'meerkat',
    'mockingbird',
    'mole',
    'mongoose',
    'monitor lizard',
    'monkey 🐒',
    'moose',
    'mountain goat',
    'mouse 🐭',
    'mule deer',
    'musk ox',
    'narwhal 🦄',
    'Nile crocodile',
    'nine-banded armadillo',
    'nuthatch',
    'ocelot',
    'octopus 🐙',
    'opossum',
    'orangutan 🦧',
    'orca',
    'oryx',
    'osprey',
    'ostrich',
    'otter 🦦',
    'owl 🦉',
    'oyster 🦪',
    'ox',
    'panda 🐼',
    'pangolin',
    'panther',
    'parakeet',
    'parrot 🦜',
    'partridge',
    'peacock 🦚',
    'pelican',
    'penguin 🐧',
    'peregrine falcon',
    'pheasant',
    'pig 🐖',
    'pigeon',
    'platypus',
    'plover',
    'polar bear',
    'polecat',
    'pony',
    'porcupine',
    'possum',
    'pronghorn',
    'puffin 🐧',
    'puma',
    'python',
    'quail',
    'quokka',
    'rabbit'
    'raccoon 🦝',
    'rat 🐀',
    'rattlesnake 🐍',
    'raven',
    'red-tailed hawk',
    'reindeer',
    'rhino 🦏',
    'ringtail lemur',
    'roadrunner',
    'robin',
    'rooster 🐓',
    'salamander',
    'salmon',
    'sandhill crane',
    'sandpiper',
    'savannah cat',
    'scorpion 🦂',
    'seal',
    'serval',
    'shark 🦈',
    'sheep 🐑',
    'shrew',
    'shrimp 🦐',
    'skink',
    'skunk 🦨',
    'sloth 🦥',
    'snake 🐍',
    'snowy owl',
    'sparrow',
    'spider',
    'spoonbill',
    'springbok',
    'squid 🦑',
    'squirrel',
    'starfish',
    'starling',
    'stork',
    'sugar glider',
    'sunbird',
    'sunfish',
    'swan 🦢',
    'tapir',
    'tarantula',
    'Tasmanian devil',
    'tern',
    'tiger 🐅',
    'timber wolf 🐺'
    'tortoise',
    'toucan',
    'trilobite',
    'turkey 🦃',
    'turkey vulture',
    'turtle 🐢',
    'two-toed sloth',
    'urchin',
    'uromastix',
    'velociraptor',
    'vicuna',
    'viper🐍',
    'vulture',
    'wallaby',
    'warthog',
    'water buffalo',
    'water moccasin',
    'whale 🐋',
    'wildebeest',
    'wolf 🐺',
    'wolverine',
    'wombat',
    'woodchuck',
    'woodpecker',
    'x-ray tetra',
    'yak',
    'zebra 🦓',
    
    #body organs
    'arm',
    'eye',
    'finger',
    'foot',
    'hair',
    'hand',
    'head',
    'heart',
    'knee',
    'leg',
    'nail',
    'neck',
    'nose',
    'toe',
    'tooth',

    #insect 
    'ant 🐜',
    'bee 🐝',
    'beetle',
    'butterfly 🦋',
    'caterpillar 🐛',
    'cockroach',
    'cricket 🦗',
    'damselfly',
    'dragonfly',
    'firefly',
    'flea',
    'fly',
    'grasshopper',
    'honeybee 🐝',
    'ladybug 🐞',
    'millipede',
    'mosquito 🦟',
    'moth'
    'praying mantis',
    'stick bug',
    'spider 🕷',
    'termite',
    'wasp'
    
    # clothing items
    'apron',
    'ascot',
    'ball gown',
    'bandana',
    'beanie',
    'bell-bottoms',
    'belt',
    'beret',
    'bikini 👙',
    'bennie',
    'blazer',
    'bloomer',
    'blouse',
    'blue jeans 👖',
    'boot 🥾',
    'bra',
    'caftan',
    'cap 🧢',
    'cardigan'
    'coat',
    'corset',
    'cravat',
    'crop top',
    'crown 👑',
    'diving mask 🤿',
    'dress',
    'dungaree',
    'dynamo',
    'earmuff',
    'feather boa',
    'flannel shirt',
    'flip flops',
    'frock',
    'fur coat',
    'glasses',
    'glove',
    'goggles 🥽',
    'gown',
    'habit',
    'haltertop',
    'handbag 👛',
    'hat',
    'head scarf',
    'headphone 🎧',
    'helmet',
    'hijab',
    'hoodie',
    'house shoe',
    'hotpants',
    'ice skate ⛸️',
    'jacket',
    'jeans',
    'joggers',
    'jumper',
    'jumpsuit',
    'kilt',
    'kimono 👘',
    'kippah',
    'leggings',
    'life-jacket',
    'lingerie',
    'mask',
    'mitten',
    'murse',
    'muffler',
    'necktie',
    'negligee',
    'neon fanny pack',
    'overalls',
    'pants',
    'parka',
    'party hat',
    'poncho',
    'raincoat',
    'romper',
    'sandal',
    'sari 🥻',
    'scarf',
    'shirt',
    'shoe',
    'skinny jeans',
    'skirt',
    'slipper',
    'sneaker',
    'sock 🧦',
    'stocking',
    'suit',
    'sunglasses 🕶️',
    'sweater',
    't-shirt 👕',
    'tie',
    'top hat 🎩',
    'toque',
    'turtle neck',
    'tutu',
    'tuxedo',
    'underpants',
    'undershirt',
    'underwear',
    'uniform',
    'veil',
    'vest',
    'waistcoat',
    'wallet',
    'watch',
    'wetsuit',
    'windbreaker',
    'yeezy',


    # foods
    'almond',
    'ambrosia salad',
    'apple',
    'apple pie 🥧',
    'applesauce',
    'apricot',
    'arroz con leche',
    'arroz con pollo',
    'arugula',
    'asparagus',
    'avocado',
    'bacon 🥓',
    'bagel 🥯',
    'baguette 🥖',
    'banana split',
    'banana 🍌',
    'banana cream',
    'basil',
    'bavarian beer 🍺',
    'beet',
    'bell pepper',
    'biryani',
    'black eyed pea',
    'blackberry',
    'blueberry',
    'bok choy',
    'bologna',
    'boysenberry',
    'bread🍞',
    'broccoli',
    'brownie',
    'burrito 🌯',
    'butternut squash',
    'butter chicken',
    'cabbage',
    'cadbury egg 🍫',
    'cake',
    'candy 🍬',
    'cantaloupe',
    'carrot',
    'cashew',
    'casserole',
    'cauliflower',
    'celery',
    'cereal',
    'challah bread',
    'chard',
    'cheese 🧀',
    'cheeseburger 🍔',
    'cherry 🍒',
    'chicken and dumpling',
    'chicken dinner',
    'chicken noodle soup',
    'chicken tikka masala',
    'chili baby corn',
    'chile con carne',
    'chimichanga',
    'chocolate bar 🍫',
    'chocolate ball',
    'chole bhature',
    'chow mein',
    'chutney',
    'cinnamon,', 
    'cinnamon roll',
    'clementine',
    'coconut 🥥',
    'coffee',
    'congee',
    'cookie 🍪',
    'corn 🌽',
    'cranberry',
    'crepe',
    'croissant 🥐',
    'cucumber',
    'cupcake',
    'curry',
    'currywurst',
    'Custard 🍮',
    'cutlet',
    'dahi',
    'dosa',
    'doughnut 🍩',
    'dumpling 🥟',
    'edimame',
    'egg 🥚',
    'eggplant',
    'egg roll',
    'egg nog',
    'enchilada',
    'English muffin',
    'fajita',
    'falafel',
    'fish and chips',
    'fortune cookie 🥠',
    'french fry 🍟',
    'fried chicken 🍗',
    'fried plantain',
    'fried rice',
    'garlic bread',
    'gefilte fish',
    'gnocchi',
    'graham cracker',
    'granola',
    'grapes 🍇',
    'green apple 🍏',
    'green bean',
    'guacamole 🥑',
    'gulab jamun',
    'gumbo',
    'gyro',
    'ham',
    'hamburger',
    'ham sandwich',
    'halwa',
    'hashbrown',
    'honey',
    'hotdog 🌭',
    'huevos rancheros',
    'hummus',
    'ice cream',
    'idli sambhar',
    'jackfruit',
    'jalapeno',
    'jalebi',
    'jam',
    'jambalaya',
    'jelly',
    'kachori',
    'kale',
    'kebab',
    'kefir',
    'kheer',
    'Khia sangia',
    'khichdi',
    'kidney bean',
    'kimchi',
    'kiwi',
    'kofta',
    'lasagna',
    'lassi',
    'lechon',
    'hamburger',
    'lemonade',
    'lentils',
    'linguine',
    'lobster',
    'maal-pua',
    'macaroni and cheese',
    'mango',
    'martini 🍸',
    'mashed potatoes',
    'matzah ball',
    'meatball',
    'meatloaf',
    'melon 🍈',
    'mimosa',
    'mojito',
    'moussaka',
    'mousse',
    'mushroom',
    'muffin',
    'naan',
    'noodle',
    'omelette',
    'onion soup',
    'onion rings',
    'orange',
    'oreo 🍪',
    'oxtail',
    'pancake',
    'paneer',
    'paratha',
    'pasta',
    'pav bhaji',
    'peach 🍑',
    'peanut butter',
    'peanut',
    'pear',
    'persimmon',
    'pho',
    'pie',
    'pierogi',
    'pizza 🍕',
    'pomegranate',
    'poki bowl',
    'popcorn 🍿',
    'poutine',
    'potato',
    'potluck',
    'pretzel 🥨',
    'protein shake',
    'pulao',
    'pumpkin',
    'quesadilla',
    'quinoa',
    'rainbow cake',
    'ramen',
    'rasgulla',
    'ratatouille',
    'reuben',
    'rice',
    'rice Ball 🍙',
    'roti',
    'salad',
    'salmon',
    'salsa',
    'samosa',
    'sandwich',
    'sausage',
    'spaghetti 🍝',
    'spam',
    'spinach',
    'stroganoff',
    'sushi 🍣',
    'Szechuan',
    'taco 🌮',
    'tacobell grilled cheese burrito 🌯',
    'tandoori chicken',
    'tater tot',
    'tea ☕',
    'tiramisu',
    'toast',
    'tofu',
    'tomato soup',
    'trifle',
    'tuna',
    'udoon',
    'vada pav',
    'venison',
    'waffle 🧇',
    'walnut',
    'watermelon 🍉',
    'yoghurt',
    'ziti',
    'zucchini',


    # computer things
    'adapter',
    'antivirus software',
    'audio jack',
    'bandwidth',
    'bluetooth',
    'cable',
    'carrying bag',
    'charging cable',
    'CPU',
    'desktop',
    'dual-monitor desk setup',
    'ethernet cable',
    'external hard disk',
    'firewall',
    'graphics card',
    'hard disk',
    'HDMI',
    'heat sink',
    'joystick',
    'kernel',
    'keyboard',
    'laptop stand',
    'laptop',
    'laptop table',
    'memory card',
    'microphone',
    'monitor',
    'motherboard',
    'mouse pad',
    'pen drive',
    'port',
    'printer',
    'quad-core processor',
    'RAM',
    'ROM',
    'scanner',
    'SD card',
    'socket',
    'software',
    'speaker',
    'SSD',
    'stylus pen',
    'thumb drive',
    'trackpad',
    'usb',
    'usb charger',
    'usb hub',
    'virus',
    'webcam',
    'wireless charger',
    'wireless mouse',
    'wireless touchpad',

    # old tech
    'answering machine',
    'betamax',
    'cassette player',
    'clicky mechanical keyboard',
    'CRT computer monitor',
    'dial-up modem',
    'dot-matrix printer',
    'fax machine 📠',
    'flip phone',
    'floppy disc',
    'gramophone',
    'iMac G3',
    'landline ☎️',
    'MP3 player',
    'pagers/beeper 📟',
    'PDA',
    'phonebook',
    'portable DVD player',
    'radio',
    'rotary telephone',
    'steno machine',
    'telegraph',
    'typewriter',
    'VCR',
    'VHS',
    'walkman',
    'floppy disk',
    'keypad phone',
    'ink quil',
    'post card',
    'TV guide',

    # video game consoles
    'Adventure Vision',
    'Atari',
    'Commodore 64',
    'Dreamcast',
    'GameBoy',
    'GameBoy Color',
    'GameCube',
    'Intellivision',
    'N64',
    'NES',
    'Nintendo DS',
    'Nintendo Switch',
    'Ouya',
    'PlayStation',
    'PS Vita',
    'PS1',
    'PS2',
    'PS3',
    'PS4',
    'PS5',
    'PSP',
    'Sega',
    'Sega Game Gear',
    'Sega Genesis',
    'Sega Saturn',
    'SNES',
    'Virtual Boy',
    'Wii',
    'Wii U',
    'Xbox',
    'Xbox 360',
    'Xbox 1',
    'Xbox X',

    # nature
    'archipelago',
    'aurora',
    'beach 🏖',
    'body of water',
    'bolt of lightning ⚡',
    'breeze',
    'campfire 🔥',
    'cave',
    'cliff',
    'cloud over the sun ⛅',
    'cloud',
    'coast',
    'desert',
    'Earth 🌎',
    'drizzle',
    'flower 🌹',
    'forest',
    'hill',
    'island 🏝️',
    'lake',
    'logs',
    'meadow',
    'moon 🌑',
    'moonlit sky',
    'mountain ⛰️',
    'oak tree',
    'ocean',
    'pebble',
    'petrichor',
    'pond',
    'rain',
    'rainbow 🌈',
    'rainforest',
    'river',
    'rock',
    'sand',
    'sea',
    'seashell',
    'sky',
    'sleet',
    'snow',
    'snowflake ❄',
    'some moss',
    'star',
    'stone',
    'storm',
    'sunflower 🌻',
    'sunset',
    'swamp',
    'spring',
    'the swamp creature',
    'thunder',
    'trail in the woods',
    'volcano',
    'wasteland',
    'waterfall',
    'wind',

    # classroom objects
    'back pack',
    'bench',
    'binder clip',
    'board',
    'book',
    'box',
    'calculator',
    'chalk',
    'compass',
    'duster',
    'eraser',
    'geometry box',
    'highlighter',
    'liquid paper',
    'lunch box',
    'marker',
    'notebook',
    'paint',
    'pen',
    'pencil case',
    'pencil sharpener',
    'pencil',
    'protractor',
    'ruler',
    'scissor',
    'stapler',
    'stencil',
    'water bottle',
    'whiteboard',

    # rpg classes\skins
    'assassin',
    'archer',
    'bard',
    'berserker',
    'boss',
    'cleric',
    'dragon 🐲',
    'fae',
    'fighter',
    'ghost',
    'ghoul',
    'immortal',
    'king',
    'knight',
    'mage',
    'mortal',
    'necromancer',
    'prince',
    'princess',
    'queen',
    'rogue',
    'shadowknight',
    'sorcerer',
    'summoner',
    'vampire',
    'vigilante',
    'warlock',
    'werewolf',
    'witch',
    'witcher',
    'wizard',
    

    # goofy things
    # NOTE: must make sense after "{adjective} {label}" (example: tiny queer [something])
    '3 day old opened can of tuna',
    'app that has stories but really shouldn\'t have them',
    'automatic kitty litter box',
    'barely-functioning homemade water bottle bong',
    'blurry photo of feet from an @OnlyFans subscription',
    'cake that perfectly resembles an intricate knitted blanket',
    'castle',
    'child asking "why" for the fiftieth time',
    'color',
    'graphic novel memoir',
    'hand drawn picture of a stick family hanging in The Louvre',
    'horribly biased machine learning code out to screw over the most vulnerable',
    'indie song about friendship',
    'ladle',
    'lighthouse in the darkness',
    'mitten still on the ground from last winter',
    'mom in sweatpants',
    'mostly slept through @Netflix series',
    'mysterious burrito with no owner',
    'mysterious piñata hanging in a hallway',
    'null bus',
    'null haus',
    'old folk-tale that kept you up at night',
    'outdoor @OnePeloton',
    'partially eaten chicken salad sandwich',
    'pink bra strap',
    'pipe made out of an apple',
    'ray of light in the distance',
    'scream into the void',
    'stack of half-finished side projects',
    'subscription box of cat toys',
    'surprise casserole',
    'treadmill, but only for using outside',
    'treekisser',
    'twitter meme trend',
    'unintended consequence of a homogenous software engineering team',
    'wheelchair-bomb',
    'wrongness parfait',

    # types of movies
    'action movie',
    'anime movie',
    'adventure movie',
    'animation movie',
    'comedy movie',
    'cartoon movie',
    'dramatic movie',
    'family movie',
    'fiction movie',
    'historical movie',
    'horror movie',
    'mystery movie',
    'non-fiction movie',
    'romance movie',
    'romantic movie',
    'romcom movie',
    'suspense movie',
    'sci-fi movie',
    'thriller movie',
    
    # types of video games
    'action game',
    'action-adventure game',
    'adventure game',
    'role playing game',
    'simulation game',
    'strategy game',
    'sports game',
    'puzzle game',
    'idle game',

    # grooming items
    'bodywash',
    'cleanser',
    'comb',
    'curling-iron',
    'epilator',
    'face scrub',
    'face wash',
    'foot massager',
    'hair crimper',
    'hair dryer',
    'lip gloss',
    'mirror',
    'mouthwash',
    'razor',
    'red lipstick',
    'sanitary napkin',
    'sanitizer',
    'serum',
    'soap',
    'tampon',
    'toothbrush',
    'toothpaste',
    'trimmer',
    'wax-strip',

    # sports things
    'abmat',
    'assault bike',
    'archery target',
    'badminton net',
    'badminton racket',
    'barbell',
    'baseball field',
    'basketball',
    'batting glove',
    'billiards stick',
    'bumper plate',
    'carom',
    'chess board',
    'cricket paddle',
    'cricket bat',
    'cricket ball',
    'dartboard',
    'discuss',
    'dodgeball',
    'dumbbell',
    'frisbee',
    'goal post',
    'golf club',
    'handball',
    'hula hoop',
    'ice hockey rink',
    'jump rope',
    'karate dojo',
    'kettlebell',
    'lacrosse stick',
    'peg board',
    'plyo box',
    'polo team',
    'racquetball court',
    'rugby ball',
    'shotput',
    'slam ball',
    'snorkel gear',
    'soccer goalie',
    'softball bat',
    'speed rope',
    'spikes',
    'squash team',
    'table tennis paddle',
    'tennis court',
    'tug of war rope',
    'volleyball net',
    'water polo',
    'wicket',
    'yoke'

    # fashion trends
    'chelsea boot',
    'cuffed pants and sleeves',
    'tight-rolled pants',
    'asymmetrical undercut',
    'septum piercing',
    'rolled pant legs',
    'folded shirt sleeves',
    'cuffed jeans',
    'oversized jeans',
    'Oversized Victorian Sleeves',
    'Maxi Faux Leather Coats',
    'Ripped Stockings',
    'Faux Fur Sandals',
    'Bucket Hats',
    'Shrunken Bags',
    'baggy trousers',
    'poofy shoulders',

    # queer things
    '@autostraddle article',
    'chosen family',
    'drag king',
    'drag queen',
    'drag brunch',
    'french cuff',
    'gogo boy',
    'newest issue of @ftmmagazine',
    'newly released book chosen for the Stonewall Book Awards (@GLBTRT)',
    'old issue of @TheAdvocateMag',
    'Sunday brunch',
    'tight-rolled pant',
    'wall plastered with varying pride flags',
    '@autostraddle article',
]
