'''
tweet_adjectives.py: list of adjectives used to build tweet.py
11 September 2020
Vicki Langer (@vicki_langer)
'''

# TODO: add more adjectives, in alphabetical order
# NOTE: must make sense in "{adjective} {label} {noun}" (example: [adjective] queer book)
# NOTE: must fit in a tweet, so not longer than this line -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|

adjectives = [
    'adorable ',
    'aesthetical',
    'aggressive',
    'alcoholic',
    'ambidextrous',
    'angelic',
    'animated',
    'bubbly',
    'bad',
    'brittle',
    'cautious',
    'clever',
    'comical',
    'curious',
    'dead',
    'diligent',
    'exuberant',
    'fabulous',
    'fantastic',
    'fertile',
    'fragile',
    'funky',
    'hard',
    'harmful',
    'haughty',
    'high af',
    'hilarious',
    'honest',
    'jocose',
    'jocular',
    'laughable',
    'lively',
    'ludicrous',
    'mushy',
    'naughty',
    'obsolete',
    'puffy',
    'puzzled',
    'quizzical',
    'rustic',
    'ruthless',
    'salty',
    'sassy',
    'sly',
    'smelly',
    'sober',
    'somber',
    'stingy',
    'swanky',
    'terrific',
    'testy',
    'tragic',
    'wacky',
    'whimsical',
    'witty',
    'x-rated',

    # touch feels
    'bumpy',
    'crusty',
    'damp',
    'dry',
    'dusty',
    'encrusted',
    'filthy',
    'flaky',
    'freezing',
    'furry',
    'fuzzy',
    'greasy',
    'icy',
    'loose',
    'painful',
    'prickly',
    'rough',
    'shaggy',
    'silky',
    'slick',
    'slimy',
    'slippery',
    'smooth',
    'sticky',
    'tender',
    'tight',
    'warm',
    'wet',

    # appearance
    'beautiful',
    'blushing',
    'bright',
    'butch',
    'chubby',
    'clumsy',
    'cracked',
    'dapper',
    'debonair',
    'dreamy',
    'elegant',
    'ethereal',
    'exhausted',
    'femme',
    'glamorous',
    'gorgeous',
    'gross',
    'grotesque',
    'handsome',
    'iconic',
    'lanky',
    'mismatched',
    'murky',
    'muscular',
    'plump',
    'quaint',
    'sexy',
    'shiny',
    'skinny',
    'sparkly',
    'spotless',
    'spotted',
    'spry',
    'striped',
    'tacky',
    'ugly',

    # shapes
    'blobby',
    'broad',
    'chubby',
    'circular',
    'crooked',
    'curved',
    'deep',
    'flat',
    'fluffy',
    'narrow',
    'oval',
    'phat',
    'rotund',
    'round',
    'shallow',
    'skinny',
    'steep',
    'stout',
    'thick',
    'triangular',
    'wonky',

    # tastes
    'acidic',
    'acrid',
    'bitter',
    'bland',
    'crispy',
    'crunchy',
    'delicious',
    'fruity',
    'greasy,'
    'juicy',
    'lemony',
    'minty',
    'mushy',
    'pickled',
    'ripe',
    'salty',
    'savory',
    'scrumptious',
    'sour',
    'spicy',
    'sugary',
    'sweet',
    'tangy',
    'yummy',

    # sounds
    'audible',
    'brassy',
    'cacophonous',
    'crashing',
    'deafening',
    'dulcet',
    'ear-splitting',
    'echoing',
    'euphonious',
    'explosive'
    'faint',
    'grinding',
    'hissing',
    'hoarse',
    'howling',
    'hush',
    'husky',
    'insistent',
    'lilting',
    'loud',
    'melodic',
    'moaning',
    'muffled',
    'mute',
    'noisy',
    'percussive',
    'piercing',
    'pitchy',
    'plaintive',
    'pulsating',
    'pure',
    'psychedelic',
    'purring',
    'raucous',
    'raspy',
    'resonant',
    'rhythmic',
    'riotous',
    'roaring',
    'rowdy',
    'rumbling',
    'sharp',
    'shrill',
    'soft',
    'sonorous',
    'staccato',
    'thunderous',
    'tonal',
    'tumultuous',
    'uproarious',
    'whirling',
    'whistling',

    # sizes
    'average',
    'beefy',
    'boundless',
    'brawny',
    'broad',
    'bulky',
    'chubby',
    'chunky',
    'colossal',
    'compact',
    'curvy',
    'emaciated',
    'endless',
    'enormous',
    'expansive',
    'extensive',
    'gargantuan',
    'gigantic',
    'ginormous',
    'hefty',
    'huge',
    'hulking',
    'immeasurable',
    'immense',
    'infinitesimal',
    'jumbo',
    'lanky',
    'large',
    'lean',
    'life-size',
    'limitless',
    'little',
    'mammoth',
    'massive',
    'meager',
    'measly',
    'microscopic',
    'miniature',
    'miniscule',
    'minute',
    'narrow',
    'paltry',
    'petite',
    'pint-size',
    'pocket-size',
    'puny',
    'rotund',
    'scanty',
    'scraggy',
    'scrawny',
    'short',
    'sizable',
    'skeletal',
    'skimpy',
    'slender',
    'stocky',
    'sturdy',
    'tall',
    'teensy',
    'teeny-weeny',
    'tiny',
    'titanic',
    'towering',
    'trifling',
    'vast',
    'wee',
    'whopping',

    # colors
    'amaranth',
    'amber',
    'arsenic-colored',
    'ash',
    'ash',
    'ashy',
    'azure',
    'azure',
    'burgundy',
    'black ',
    'carmine',
    'cedar',
    'cerulean',
    'chartreuse',
    'crimson',
    'dandelion',
    'drab',
    'dull',
    'emerald',
    'fallow',
    'fawn',
    'fuschia',
    'goldenrod',
    'gray',
    'hot pink',
    'indigo',
    'ivory',
    'jade',
    'lavender',
    'lime',
    'magenta',
    'mauve',
    'mocha',
    'moss',
    'multicolored',
    'mustard-colored',
    'navy',
    'ochre',
    'olive',
    'orangish',
    'orchid',
    'peach',
    'really dark black',
    'rosy',
    'royal',
    'ruby',
    'sage',
    'salmon',
    'sapphire',
    'scarlet',
    'sepia',
    'silver',
    'teal',
    'tuscany',

    # cold adjectives
    'algid',
    'austere',
    'benumbed',
    'biting',
    'bitter',
    'bitterly cold',
    'bleak',
    'bone-chilling',
    'bracing',
    'brisk',
    'brumal',
    'chilly',
    'congealed',
    'cool',
    'cryogenic',

    # warm adjectives
    'agreeable',
    'balmy',
    'blood-warm',
    'clement',
    'homey',
    'lukewarm',
    'mellow',
    'mild',
    'moderate',
    'pleasant',

    # weather and temperature
    'cloudy',
    'cold',
    'cool',
    'foggy',
    'frozen',
    'hot',
    'rainy',
    'snowy',
    'stormy',
    'sunny',
    'windy',

    # adverb and adjective pairs
    'perfectly splendid',
    'very similar',
    'well aware',
    'fast asleep',
    
    # character traits
    'decadent',
    'dogmatic',
    'fidgety',
    'intimidating',
    'irritable',
    'sagacious',
    'strict',
    'strong'
    ]
